export const ProductsDetails = [
  {
    id: "product1",
    picture: "",
    title: "Fumigadora De 2 Cuerpos Desmotable",
    discountOrange: 25,
    discountGreen: "",
    amount: "$5.099",
    prevamount: "$7.000",
    mostsell: false,
    colors: "",
    truck: false,
    fastship1: true,
    fastship2: false,
    full: true,
  },

  {
    id: "product2",
    picture: "",
    title: "Vaporera desmontable",
    discountOrange: "",
    amount: "$7.389",
    prevamount: "$8.900",
    discountGreen: 20,
    mostsell: false,
    colors: "",
    truck: true,
    fastship1: false,
    fastship2: false,
    full: false,
  },

  {
    id: "product3",
    picture: "",
    title: "Celular Motorola E7",
    discountOrange: "",
    amount: "$21.999",
    prevamount: "$23.400",
    discountGreen: 21,
    mostsell: true,
    colors: 3,
    truck: false,
    fastship1: false,
    fastship2: true,
    full: false,
  },
];
